version: '3.2'
services:
  db:
    image: postgres:12
    restart: always
    volumes:
      - ./pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  app:
    build: .
    image: "registry.sixtyeightplus.one/partpicker"
    depends_on:
      - 'db'
    ports:
      - "4008:4000"
      - "4028:4369"
      - "4228:4228"
    hostname: "miatapartpicker.gay"
    environment:
      RELEASE_DISTRIBUTION: "name"
      RELEASE_NODE: "partpicker@miatapartpicker.gay"
